name = "bisand-blog-test"
compatibility_date = "2022-09-10"

[site]
bucket = "./dist"

[env.production]
name = "test-blog-site"
route = "https://test-blog.biseth.com/*"

[env.preview]
name = "test-blog-site-staging"
route = "https://staging.test-blog.example.com/*"

kv_namespaces = [
    { binding = "images", preview_id = "aaf56cc016f042ab91636d59b4875776", id = "34c5d7c3bbab404bb9777a058ef0a2cf" },
    { binding = "bisand-blog", preview_id = "3e094d827b1f436d9cd16cdd3f860f24", id = "be707cd3dec2440085d7cc08a06e90b5" }
]
